### ISSUE TITLE
Upload continues indefinitely

### ISSUE THREAD

**Issue by scarm01** [owainjones74/filament-chunked-file-uploads#1]
Hi,

with some large files (>500MB) the upload will continue indefinitely and never end.
The temporary file that is created in the storage folder grows and grows. It will at some point become bigger than the file you were uploading and continue to grow in size.

Did anybody else experienced this issue?

**Comment by 0wain** [comment]
Hey,

Thanks for opening an issue about this. I'll investigate it today.

It sounds like the client just continues to send chunks, so maybe there is a bug that causes some kind of recursive issue?

Are you able to replicate this with multiple files of difference sizes over 500MB? Also, what chunk size are you setting?

Thanks again for reporting this.

**Comment by scarm01** [comment]
Hi,

this problem is occurring only when I upload big file (like 500MB files).
This issue is not present with smaller files (about 100-200MB in size).

It happens with every file over 500MB. I think that there might be some issue with file chunking. The clients continues to create chunks and never ends.

I tried with different chunk sizes, from 50MB to 5MB but I'm still experiencing this issue.

If you can explain me really quickly how to recompile the js file I'll try to help you to find the issue. Yesterday I added some `console.log()` inside the js file in `resources` but they are getting ignores. I think that's because the compiled file is being loaded.

Thank you :)

**Comment by 0wain** [comment]
Hey, I've not forgotten about this. Still debugging some stuff, will also provide you some build instructions very soon.

**Comment by 0wain** [comment]
Hey,

Finally got round to testing this.

I was able to successfully upload a 800MB file, seemed to process fine for me.

![Screenshot 2023-11-29 at 22 02 13](https://github.com/owainjones74/filament-chunked-file-uploads/assets/15251181/636cf8ac-52e8-4221-a6b3-5a19c0ee32b5)

I'm running Firefox, are you possibly running a different browser? Also what file format are you uploading?

If you want to do some testing yourself, you can recompile the javascript file by running `node bin/build.js --dev` from inside the route folder of this project. You can probably just go to this package from inside your composer folder and run the command and it should use the updated version.

**Comment by scarm01** [comment]
I tested it with Chrome, I'll try again with firefox and let you know.
I was uploading a Mp4 file.

**Comment by 0wain** [comment]
Hi, just following up to see if you managed to get any luck with debugging this?

**Comment by ahmadina** [comment]
Same problem, why this issue closed?

**Comment by 0wain** [comment]
Hi @ahmadina,

The issue was closed because I am unable to replicate this bug and @scarm01 seemed to have lost interest in the report, so there was nothing more that I could do.

If you're able to provide reproduction steps, including the size of the file and the file type, I can attempt to replicate this bug. But without additional information, there is little more that can be done.
