### ISSUE TITLE
Do you have the possibility of implementing v2?

### ISSUE THREAD

**Issue by elmudometal** [owainjones74/filament-chunked-file-uploads#2]
I am needing this functionality in v2 and I can't get anything similar

do you have s3 support? or test?

**Comment by 0wain** [comment]
Hey,

Thanks for reaching out.

Do you know how different the file upload functionality is in v2 compared to v3? It could possibly be a case of me just needing to bring the dependancy version down? I'll take a look at this and get back to you.

**Comment by elmudometal** [comment]
I tested it on a fork, and downgrade the composer json
         "filament/support": "^2.0",
but the file-upload-chunked view component is based on file-upload.blade.php from filamente V3 and varies a lot in relation to file-upload.blade.php V2

in the FilamentFileUploadChunkedServiceProvider change
FilamentAsset::register([
             AlpineComponent::make('file-upload-chunked', __DIR__.'/../dist/file-upload-chunked.js'),
         ], 'owainjones74/filament-file-upload-chunked');

to


     protected array $scripts = [
         'file-upload-chunked' => __DIR__.'/../dist/file-upload-chunked.js',
     ];
